#!/bin/bash

VCF_IN=../../PB_ONT/longtr_merged_PB_ONT_addEND.vep.trimSamples.addInfo.vcf.gz
VEP_OUT=vep.tsv

date

echo "Making VEP table..."

#echo -n -e "CHROM\tPOS\tEND\tID\tConsequence\tIMPACT\tSYMBOL\tGENE\tBIOTYPE\tEXON\tINTRON\tDISTANCE\tSTRAND\tOverlapBP\tOverlapPC\tTSSDistance\tGENCODE\tGNOCCHI\tFB_PR_ENH_M\tFB_PR_ENH_F\tFANTOM_ENH\n" > $VEP_OUT
#
#bcftools +split-vep -X -c Gene,BIOTYPE,SYMBOL,IMPACT,EXON,INTRON,Consequence,DISTANCE,STRAND,OverlapBP,OverlapPC,TSSDistance,GENCODE,GNOCCHI,FB_PR_ENH_M,FB_PR_ENH_F,FANTOM_ENH -f '%CHROM\t%POS\t%END\t%ID\t%Consequence\t%IMPACT\t%SYMBOL\t%Gene\t%BIOTYPE\t%EXON\t%INTRON\t%DISTANCE\t%STRAND\t%OverlapBP\t%OverlapPC\t%TSSDistance\t%GENCODE\t%GNOCCHI\t%FB_PR_ENH_M\t%FB_PR_ENH_F\t%FANTOM_ENH\n' $VCF_IN >> $VEP_OUT

#**echo -n -e "CHROM\tPOS\tEND\tID\tGENCODE\tZS_SAMPLES\tZS_SAMPLES_NUM\tSN_GB\tDENOVO\tDENOVO_GB\tDENOVO_NUM\tDENOVO_MAT\tDENOVO_MAT_GB\tDENOVO_MAT_NUM\tDENOVO_PAT\tDENOVO_PAT_GB\tDENOVO_PAT_NUM\tLARGE25_DEV_GB\tLARGE50_DEV_GB\tLARGE100_DEV_GB\tLARGE500_DEV_GB\tMEAN_GB\tSTD_GB\tQ95_SAMPLES_GB\tQ90_SAMPLES_GB\tQ80_SAMPLES_GB\tQ70_SAMPLES_GB\tHP1_SAMPLES_PDP\tHP2_SAMPLES_PDP\tHEM_SAMPLES_DP\tGNOCCHI\tFB_PR_ENH_M\tFB_PR_ENH_F\tFANTOM_ENH\tConsequence\tIMPACT\tSYMBOL\tGENE\tBIOTYPE\tDISTANCE\tTSSDistance\tEXON\tINTRON\n" > $VEP_OUT
#**
#**bcftools +split-vep -X -c Gene,BIOTYPE,SYMBOL,IMPACT,EXON,INTRON,Consequence,DISTANCE,STRAND,OverlapBP,OverlapPC,TSSDistance,GENCODE,GNOCCHI,FB_PR_ENH_M,FB_PR_ENH_F,FANTOM_ENH -f '%CHROM\t%POS\t%END\t%ID\t%GENCODE\t%ZS_SAMPLES\t%ZS_SAMPLES_NUM\t%SN_GB\t%DENOVO\t%DENOVO_GB\t%DENOVO_NUM\t%DENOVO_MAT\t%DENOVO_MAT_GB\t%DENOVO_MAT_NUM\t%DENOVO_PAT\t%DENOVO_PAT_GB\t%DENOVO_PAT_NUM\t%LARGE25_DEV_GB\t%LARGE50_DEV_GB\t%LARGE100_DEV_GB\t%LARGE500_DEV_GB\t%MEAN_GB\t%STD_GB\t%Q95_SAMPLES_GB\t%Q90_SAMPLES_GB\t%Q80_SAMPLES_GB\t%Q70_SAMPLES_GB\t%HP1_SAMPLES_PDP\t%HP2_SAMPLES_PDP\t%HEM_SAMPLES_DP\t%GNOCCHI\t%FB_PR_ENH_M\t%FB_PR_ENH_F\t%FANTOM_ENH\t%Consequence\t%IMPACT\t%SYMBOL\t%Gene\t%BIOTYPE\t%DISTANCE\t%TSSDistance\t%EXON\t%INTRON' $VCF_IN >> $VEP_OUT

echo -n -e "CHROM\tPOS\tEND\tID\tGENCODE\tPERIOD\tZS_SAMPLES\tZS_SAMPLES_NUM\tZS_SAMPLES_PB\tZS_SAMPLES_ONT\tSN_GB\tDENOVO\tDENOVO_GB\tDENOVO_NUM\tDENOVO_MAT\tDENOVO_MAT_GB\tDENOVO_MAT_NUM\tDENOVO_PAT\tDENOVO_PAT_GB\tDENOVO_PAT_NUM\tLARGE25_DEV_GB\tLARGE50_DEV_GB\tLARGE100_DEV_GB\tLARGE500_DEV_GB\tMEAN_GB\tSTD_GB\tQ90_SAMPLES_GB\tHP1_SAMPLES_PDP\tHP2_SAMPLES_PDP\tHEM_SAMPLES_DP\tGNOCCHI\tFB_PR_ENH_M\tFB_PR_ENH_F\tFANTOM_ENH\tConsequence\tIMPACT\tSYMBOL\tGENE\tBIOTYPE\tDISTANCE\tTSSDistance\tEXON\tINTRON\n" > $VEP_OUT

bcftools +split-vep -X -c Gene,BIOTYPE,SYMBOL,IMPACT,EXON,INTRON,Consequence,DISTANCE,STRAND,OverlapBP,OverlapPC,TSSDistance,GENCODE,GNOCCHI,FB_PR_ENH_M,FB_PR_ENH_F,FANTOM_ENH -f '%CHROM\t%POS\t%END\t%ID\t%GENCODE\t%PERIOD\t%ZS_SAMPLES\t%ZS_SAMPLES_NUM\t%ZS_SAMPLES_PB\t%ZS_SAMPLES_ONT\t%SN_GB\t%DENOVO\t%DENOVO_GB\t%DENOVO_NUM\t%DENOVO_MAT\t%DENOVO_MAT_GB\t%DENOVO_MAT_NUM\t%DENOVO_PAT\t%DENOVO_PAT_GB\t%DENOVO_PAT_NUM\t%LARGE25_DEV_GB\t%LARGE50_DEV_GB\t%LARGE100_DEV_GB\t%LARGE500_DEV_GB\t%MEAN_GB\t%STD_GB\t%Q90_SAMPLES_GB\t%HP1_SAMPLES_PDP\t%HP2_SAMPLES_PDP\t%HEM_SAMPLES_DP\t%GNOCCHI\t%FB_PR_ENH_M\t%FB_PR_ENH_F\t%FANTOM_ENH\t%Consequence\t%IMPACT\t%SYMBOL\t%Gene\t%BIOTYPE\t%DISTANCE\t%TSSDistance\t%EXON\t%INTRON' $VCF_IN >> $VEP_OUT

date

