#!/bin/bash

VCF_IN=../PB_ONT/longtr_merged_PB_ONT_addEND.vep.trimSamples.addInfo.vcf.gz
VEP_OUT=vep.tsv

date

echo "Making VEP table..."

#echo -n -e "CHROM\tPOS\tEND\tID\tConsequence\tIMPACT\tSYMBOL\tGENE\tBIOTYPE\tEXON\tINTRON\tDISTANCE\tSTRAND\tOverlapBP\tOverlapPC\tTSSDistance\tGENCODE\tGNOCCHI\tFB_PR_ENH_M\tFB_PR_ENH_F\tFANTOM_ENH\n" > $VEP_OUT
#
#bcftools +split-vep -X -c Gene,BIOTYPE,SYMBOL,IMPACT,EXON,INTRON,Consequence,DISTANCE,STRAND,OverlapBP,OverlapPC,TSSDistance,GENCODE,GNOCCHI,FB_PR_ENH_M,FB_PR_ENH_F,FANTOM_ENH -f '%CHROM\t%POS\t%END\t%ID\t%Consequence\t%IMPACT\t%SYMBOL\t%Gene\t%BIOTYPE\t%EXON\t%INTRON\t%DISTANCE\t%STRAND\t%OverlapBP\t%OverlapPC\t%TSSDistance\t%GENCODE\t%GNOCCHI\t%FB_PR_ENH_M\t%FB_PR_ENH_F\t%FANTOM_ENH\n' $VCF_IN >> $VEP_OUT

echo -n -e "CHROM\tPOS\tEND\tID\tGENCODE\tZS_SAMPLES\tZS_SAMPLES_NUM\tSN_GB\tDENOVO\tDENOVO_GB\tDENOVO_NUM\tDENOVO_MAT\tDENOVO_MAT_GB\tDENOVO_MAT_NUM\tDENOVO_PAT\tDENOVO_PAT_GB\tDENOVO_PAT_NUM\tLARGE50_DEV\tLARGE50_DEV_GB\tLARGE50_DEV_NUM\tLARGE100_DEV\tLARGE100_DEV_GB\tLARGE100_DEV_NUM\tLARGE500_DEV\tLARGE500_DEV_GB\tLARGE500_DEV_NUM\tQ_SAMPLES_GB\tQ_SAMPLES_NUM\tGNOCCHI\tFB_PR_ENH_M\tFB_PR_ENH_F\tFANTOM_ENH\tConsequence\tIMPACT\tSYMBOL\tGENE\tBIOTYPE\tDISTANCE\tTSSDistance\tEXON\tINTRON\n" > $VEP_OUT

bcftools +split-vep -X -c Gene,BIOTYPE,SYMBOL,IMPACT,EXON,INTRON,Consequence,DISTANCE,STRAND,OverlapBP,OverlapPC,TSSDistance,GENCODE,GNOCCHI,FB_PR_ENH_M,FB_PR_ENH_F,FANTOM_ENH -f '%CHROM\t%POS\t%END\t%ID\t%GENCODE\t%ZS_SAMPLES\t%ZS_SAMPLES_NUM\t%SN_GB\t%DENOVO\t%DENOVO_GB\t%DENOVO_NUM\t%DENOVO_MAT\t%DENOVO_MAT_GB\t%DENOVO_MAT_NUM\t%DENOVO_PAT\t%DENOVO_PAT_GB\t%DENOVO_PAT_NUM\t%LARGE50_DEV\t%LARGE50_DEV_GB\t%LARGE50_DEV_NUM\t%LARGE100_DEV\t%LARGE100_DEV_GB\t%LARGE100_DEV_NUM\t%LARGE500_DEV\t%LARGE500_DEV_GB\t%LARGE500_DEV_NUM\t%Q_SAMPLES_GB\t%Q_SAMPLES_NUM\t%GNOCCHI\t%FB_PR_ENH_M\t%FB_PR_ENH_F\t%FANTOM_ENH\t%Consequence\t%IMPACT\t%SYMBOL\t%Gene\t%BIOTYPE\t%DISTANCE\t%TSSDistance\t%EXON\t%INTRON' $VCF_IN >> $VEP_OUT

date

